#!/usr/bin/env ruby

# Copyright (c) 2012-2012, John Mettraux, jmettraux@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require 'pp'


class Wag

  VERSION = '1.0.0'

  VHOME = ENV['WAG_HOME'] || '~/vagrant'
  VMAN = ENV['WAG_VMAN'] || `which VBoxManage`.strip
  VAG = ENV['WAG_VAG'] || `which vagrant`.strip

  SELF = File.basename($0)

  class Vm < Struct.new(:nick, :name, :uuid)
  end

  def print_usage

    puts %Q{
#{SELF} USAGE:

TODO
    }
  end

  def vms

    `#{VMAN} list vms`.split("\n").collect { |line|
      m = line.match(/^"([^"]+)" \{([^\}]+)\}$/)
      m ? Vm.new(m[1].split('_').first, m[1], m[2]) : nil
    }.compact
  end

  # Returns a Vm instance if there is one with the given name or nick.
  #
  def lookup_vm(s)

    vms.find { |vm| vm.name == s || vm.nick == s }
  end

  def exec(com)

    puts(com)
    Kernel.exec(com)
  end

  def vagrant_method(vm, *commands)

    exec(commands.inject([ "cd #{VHOME}/#{vm}" ]) { |a, c|
      a << "#{VAG} #{c}"
    }.join(' && '))
  end

  def vagrant_function(*args)

    exec("#{VAG} #{args.join(' ')}")
  end

  def vman_function(*args)

    args = args.first if args.first.is_a?(Array)

    exec("#{VMAN} #{args.join(' ')}")
  end

  PREFIXES = %w[ vm_ vf_ mm_ mf_ wf_ ]

  def lookup_rmeths(args)

    args[0, 2].collect do |a|
      PREFIXES.collect { |pref|
        meth = pref + a.gsub(/-/, '_')
        self.respond_to?(meth) ? meth : nil
      }.compact
    end
  end

  def get_method(a); (a || []).find { |e| e.match(/^.m_/) }; end
  def get_function(a); (a || []).find { |e| e.match(/^.f_/) }; end

  # The "run" method
  #
  def run

    return print_usage if ARGV.size < 1

    vm = lookup_vm(ARGV[0])

    ARGV << 'up_and_ssh' if vm && ARGV[1].nil?

    rmeths = lookup_rmeths(ARGV)

    if vm && m = get_method(rmeths[1])

      send(m, vm, ARGV[1..-1])

    elsif f = rmeths.find { |rms| get_function(rms) }

      send(f.first, ARGV)

    else

      com = vm ? ARGV[1] : ARGV[0]

      raise ArgumentError.new(
        "unknown command #{com.inspect} " +
        "- try running \"#{SELF} help\"")
    end
  end

  #
  # the commands

  def wf_help(args)

    print_usage
  end

  def wf__v(args)

    puts VERSION
  end

  alias wf___version wf__v

  def wf__consts(args)

    self.class.constants.sort.each do |con|
      puts "#{con}: #{self.class.const_get(con).inspect}"
    end
  end

  # TODO: document me
  #
  def mm_poweroff(vm, args)

    vman_function('controlvm', vm.name, 'poweroff')
  end

#  def flatten(type, args)
#
#    args.collect { |e|
#      if e.is_a?(Array)
#        type == :nick ? e.first : e.last
#      else
#        e
#      end
#    }
#  end
#
#  def man(args)
#
#    vman_function(flatten(:vm, args))
#  end

  def wf_vms(args)

    format = "%-19s %-19s %-19s\n"

    printf(format, *%w[ NICK NAME UUID ])

    vms.each do |vm|
      printf(format, *[ vm.nick, vm.name, vm.uuid ])
    end
  end

  %w[ box ].each do |c|

    class_eval %Q{
      def vf_#{c}(args)
        vagrant_function(*[ #{c.inspect}, *args ])
      end
    }
  end

  def vm_up_and_ssh(vm, args)

    vagrant_method(vm.nick, 'up', 'ssh')
  end

  %w[ up suspend resume status halt ssh ssh_config ].each do |c|

    class_eval %Q{
      def vm_#{c}(vm, args)
        vagrant_method(vm.nick, #{c.inspect})
      end
    }
  end
end

Wag.new.run #if $0 == __FILE__

